### ISSUE TITLE
[BUG] Please update examples and documentaiton

### ISSUE THREAD

**Issue by Jeansen** [opensearch-project/opensearch-k8s-operator#800] opened 2024-05-05 13:56 UTC
Obviously documentations is quite off track. Starting with the README, it still references version 2.3 although we are already at 2.6. The examples in the examples folder using CRs still reference OpenSearch version 2.3.0. Current version is 2.13.0! And with the breaking changes introduced in 2.12.0 it is not clear, how to do this in the operator CR. I'd be happy to see some updates here.

**Comment by dtaivpp** [comment] 2024-05-12 01:37
@Jeansen this is a solid callout. I am working through some of this. Which change for 2.12 are your referring to? The new default password policies?

**Comment by dtaivpp** [comment] 2024-05-12 01:42
Also, @prudhvigodithi do you think it's worth keeping some of the older examples around? I was thinking we could organize into: 

```bash 
opensearch-operator
    L examples
        L 2.X
        |    - example_a.yml 
        |    - example_b.yml

**Comment by Jeansen** [comment] 2024-05-12 08:19
> @Jeansen this is a solid callout. I am working through some of this. Which change for 2.12 are your referring to? The new default password policies?

@dtaivpp in my case, yes. But in general - like I wrote - there are also lot's of versions mentioned in the examples which are rather old.. Organizing examples into folders makes sense. One could also rename the files including a versions, but that IMHO makes the list quite long. Having folders is much more organized.

**Comment by dtaivpp** [comment] 2024-05-12 13:14
@prudhvigodithi maybe we just support latest for each major version? Then we can template it a bit better and test these.

**Comment by Jeansen** [comment] 2024-05-14 14:52
@dtaivpp everything that works for you. But with respect to cloud technologies, I agree that it might be reasonable to only support the latest version for each major (supported) versions. After all, it's all about rolling releases in the cloud ;-)

**Comment by prudhvigodithi** [comment] 2024-05-14 15:09
[Triage]
Hey @dtaivpp and @Jeansen, I got the PR merged related to the compatibility matrix https://github.com/opensearch-project/opensearch-k8s-operator/pull/792. Moving forward as we prepare of the release, along with the compatibility matrix we should go ahead and update the examples and documentation accordingly.
Adding @swoehrl-mw @salyh @bbarani

**Closed** 2024-06-05 10:28 UTC
Labels: documentation

**Comment by Jeansen** [comment] 2024-06-05 20:51
Cool, thanks. I had not expected it to be as easy as increasing numbers. But what about the new  the new default password policies? Has there been anything added to the docs (in another MR)?

**Comment by prudhvigodithi** [comment] 2024-06-05 21:03
Hey @Jeansen please check here https://github.com/opensearch-project/opensearch-k8s-operator/issues/703#issuecomment-1942311512, operator handles the security settings of the cluster and would not impact the new default password, the process is still the same for updating the admin password [Custom Admin User](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#custom-admin-user).
Thank you 
@getsaurabh02 @swoehrl-mw

**Comment by danielkubat** [comment] 2024-06-14 14:04
@Jeansen @prudhvigodithi check https://github.com/opensearch-project/opensearch-k8s-operator/issues/759

operator is unable to handle security settings of admin user and there is even WIP PR opened by @nijave: https://github.com/opensearch-project/opensearch-k8s-operator/pull/816

problem is, that the issue is not reprodusible when upgrading cluster and in CI of this repo, which doesn't mean that the issue does not exists.

**Comment by nijave** [comment] 2024-06-14 14:33
> @Jeansen @prudhvigodithi check #759
> 
> operator is unable to handle security settings of admin user and there is even WIP PR opened by @nijave: #816
> 
> problem is, that the issue is not reprodusible when upgrading cluster and in CI of this repo, which doesn't mean that the issue does not exists.

Ideally need to figure out what the difference is. Seems something related to this security setup shell script inside the OpenSearch image (there's something causing it to run which then enforces the user restrictions and breaks for people but it doesn't seem to run in the CI environment)

**Comment by Jeansen** [comment] 2024-06-15 19:57
@nijave Well, so far I was able to to test it but I've prepared everything regarding the custom password, with respect to @prudhvigodithi 's hint. I'll report as soon as I can test it, but am currently in head-deep preparing for my CKS Exam.
